[SERVICE]
    Flush         5
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
    Name              tail
    Tag               pulse.backend
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker_json
    Refresh_Interval  5
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On
    DB                /fluent-bit/etc/tail_db.pos

[FILTER]
    Name      grep
    Match     pulse.backend
    Regex     log .*pulse-backend.*

[FILTER]
    Name      parser
    Match     pulse.backend
    Key_Name  log
    Parser    pino_json
    Reserve_Data On
    Preserve_Key On

[OUTPUT]
    Name            stdout
    Match           pulse.backend
    Format          json_lines

[OUTPUT]
    Name            lts
    Match           pulse.backend
    Region          ${LTS_REGION:-cn-north-4}
    LTS_Group_ID    ${LTS_GROUP_ID}
    LTS_Stream_ID   ${LTS_STREAM_ID}
    Access_Key_ID   ${LTS_AK}
    Secret_Access_Key ${LTS_SK}
